spring.datasource.url=jdbc:postgresql://92.119.126.127:5432/billbuddy_db
spring.datasource.username=postgres
spring.datasource.password=db@Rack

spring.jpa.hibernate.ddl-auto=update
server.port=8090
bpj4.securityKey=SECURITYSECURITY
bpj4.securityIv=SECURITY